### ISSUE TITLE
[FEAT] 이미지 업로드 버튼 일회성 개선

### ISSUE THREAD

**Issue by JiWhyeon** [9oormthon-univ-swu/2024_FINAL_STARCAPSULE_FE#35]
### 구현 예정 사항

- 이미지를 업로드하면 다시 수정할 수 없다.
- [ ]  업로드된 이미지 클릭 시, 이미지 바꿀 수 있도록 개선

**Comment by SaltySalt77** [comment]
그러고보니 이거 <Button>에 `component={"labael"}` 넣어주면 되었던 것으로 기억해서 찾아봤는데, 이렇게 수정하면 될 것 같아요!
[file upload button - mui](https://mui.com/material-ui/react-button/#file-upload)
